import type { Metadata } from "next";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import { Noto_Sans_Arabic, Cairo } from "next/font/google";
import Header from "@/layout/Header";
import ScrollToTopBtn from "@/components/ui/ScrollToTopBtn";
import Footer from "@/layout/Footer";

const noto = Noto_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  variable: "--font-noto",
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["600", "700"],
  display: "swap",
  variable: "--font-cairo",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${noto.variable} ${cairo.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Header />
        {children}
        <ScrollToTopBtn />
        <Footer />
      </body>
    </html>
  );
}
